"""Pydantic schemas for LLM structured output.

Every respond_json call site maps to a model here.
LLM output is validated against these, replacing fragile .get() chains.
"""

from typing import Literal

from pydantic import BaseModel, Field


# --- Moderator ---


class ClarifyResult(BaseModel):
    """Topic clarification result."""

    valid: bool = True
    reason: str = ""
    question: str = ""
    suggestion: str = ""


class PositionItem(BaseModel):
    """A single debate position suggested by the moderator."""

    id: str
    name: str
    description: str


class PositionsResult(BaseModel):
    """Position suggestions from moderator."""

    positions: list[PositionItem] = Field(default_factory=list)


class DataClerkRecommendation(BaseModel):
    """Moderator's recommendation on whether to enable data clerk."""

    recommended: bool = False
    reason: str = ""


class RoundJudgment(BaseModel):
    """Moderator's judgment after a debate round."""

    decision: Literal["CONTINUE", "CONCLUDE"] = "CONTINUE"
    reason: str = ""
    guidance: str = ""


class PositionArgument(BaseModel):
    """One position's arguments in the minutes."""

    position: str = ""
    main_points: list[str] = Field(default_factory=list)
    defense: str = ""


class Verdict(BaseModel):
    """Final verdict in debate minutes."""

    winner: str = ""
    rationale: str = ""
    score_summary: str = ""


class DebateMinutes(BaseModel):
    """Structured debate minutes generated by moderator."""

    core_conclusion: str = ""
    position_arguments: list[PositionArgument] = Field(default_factory=list)
    key_clashes: list[str] = Field(default_factory=list)
    verdict: Verdict = Field(default_factory=Verdict)
    summary: str = ""


# --- Scorer ---


class ScoreEntry(BaseModel):
    """Score for one position in a round."""

    position_id: str = ""
    position_name: str = ""
    points: int = 0
    comment: str = ""


class ScoreResult(BaseModel):
    """Score distribution for a debate round."""

    scores: list[ScoreEntry] = Field(default_factory=list)


# --- Data Clerk ---


class SearchQueries(BaseModel):
    """Search queries decided by data clerk for a debater."""

    searches: list[str] = Field(default_factory=list)


class DataScope(BaseModel):
    """Data boundary established by moderator before debate."""

    scope_summary: str = ""
    specific_event: str = ""
    time_range: str = ""
    key_entities: list[str] = Field(default_factory=list)
    relevance_rule: str = ""


class VerifiedResults(BaseModel):
    """Data clerk verification of search results against scope and pool."""

    verified: list[dict] = Field(default_factory=list)
    rejected: list[str] = Field(default_factory=list)
    verification_note: str = ""
