"""Pydantic schemas for LLM structured output.

Every respond_json call site maps to a model here.
LLM output is validated against these, replacing fragile .get() chains.
"""

from typing import Literal

from pydantic import BaseModel, Field

# --- Moderator ---


class ClarifyResult(BaseModel):
    """Topic clarification result."""

    valid: bool = True
    rejected: bool = False
    reason: str = ""
    question: str = ""
    suggestion: str = ""
    need_data_clerk: bool = False
    clarify_round: int = 1


class PositionItem(BaseModel):
    """A single debate position suggested by the moderator."""

    id: str
    name: str
    description: str


class PositionsResult(BaseModel):
    """Position suggestions from moderator."""

    positions: list[PositionItem] = Field(default_factory=list)


class SubjectClarityCheck(BaseModel):
    """Quick check: is the main subject clear enough AND does the topic need search?"""

    subject_clear: bool = True
    needs_search: bool = True
    unclear_entities: list[str] = Field(default_factory=list)
    reason: str = ""


class DataClerkRecommendation(BaseModel):
    """Moderator's recommendation on whether to enable data clerk."""

    recommended: bool = False
    reason: str = ""


class RoundJudgment(BaseModel):
    """Moderator's judgment after a debate round."""

    decision: Literal["CONTINUE", "CONCLUDE"] = "CONTINUE"
    reason: str = ""
    guidance: str = ""


class PositionArgument(BaseModel):
    """One position's arguments in the minutes."""

    position: str = ""
    main_points: list[str] = Field(default_factory=list)
    defense: str = ""


class Verdict(BaseModel):
    """Final verdict in debate minutes."""

    winner: str = ""
    rationale: str = ""
    score_summary: str = ""


class DebateMinutes(BaseModel):
    """Structured debate minutes generated by moderator."""

    core_conclusion: str = ""
    position_arguments: list[PositionArgument] = Field(default_factory=list)
    key_clashes: list[str] = Field(default_factory=list)
    verdict: Verdict = Field(default_factory=Verdict)
    summary: str = ""


# --- Agent Thinking (ReAct-style: free-form + semantic data need) ---


class AgentThinking(BaseModel):
    """Free-form thinking output from any agent, with optional data need.

    Replaces the rigid role-specific ThinkResult schemas.
    Agents think freely about whatever they consider important.
    Strategy fields are metadata extracted FROM free-form thinking for
    cross-round state accumulation, not constraints ON the thinking process.
    """

    thinking: str = Field(
        default="",
        description="自由思考过程：分析局势、制定策略、发现关键问题等",
    )
    data_need: str = Field(
        default="",
        description="你需要什么数据？用自然语言描述，如'詹姆斯在5月7日比赛的具体得分和篮板数据'。留空表示不需要数据。",
    )
    # Strategy state metadata (only populated by debater think_before_speaking)
    my_arguments_standing: list[str] = Field(
        default_factory=list,
        description="你方仍然站得住的论点（一句话总结）",
    )
    my_arguments_refuted: list[str] = Field(
        default_factory=list,
        description="被对手成功反驳的论点（一句话总结）",
    )
    opponent_weaknesses: list[str] = Field(
        default_factory=list,
        description="发现的对手弱点或漏洞",
    )
    chosen_strategy: str = Field(
        default="",
        description="本轮策略：ATTACK/DEFEND/REDIRECT/EVIDENCE",
    )


# --- Data Clerk ---


class SearchQueries(BaseModel):
    """Search queries decided by data clerk for a debater."""

    searches: list[str] = Field(default_factory=list)


class ResearchStep(BaseModel):
    """One step in the chain-of-thought research process."""

    reasoning: str = Field(description="推理过程：从已知信息推导出下一步要搜什么")
    search_queries: list[str] = Field(
        default_factory=list, description="本步骤的搜索关键词，最多2个",
    )
    discovered_entities: list[str] = Field(
        default_factory=list,
        description="从搜索结果中发现的具名实体（日期、球队、比赛名、对手等）",
    )
    discovered_facts: list[str] = Field(
        default_factory=list,
        description="从搜索结果中提取的关键事实（带具体数值/日期）",
    )
    resolved_sub_topic: str = Field(
        default="",
        description="如果本步结果解决了一个子问题，写出答案",
    )


class ResearchPlan(BaseModel):
    """Multi-step research plan for a topic."""

    steps: list[ResearchStep] = Field(default_factory=list)


class TopicEntity(BaseModel):
    """A searchable entity extracted from the debate topic."""

    name: str = Field(description="实体名称（如'赖斯'、'Declan Rice'）")
    entity_type: str = Field(default="", description="实体类型（球员/球队/事件/地点等）")
    aliases: list[str] = Field(
        default_factory=list, description="别名（如英文名、简称）",
    )


class HiddenSubTopic(BaseModel):
    """A hidden sub-topic that needs resolution before the main question."""

    question: str = Field(description="需要先回答的子问题")
    depends_on: list[str] = Field(
        default_factory=list, description="依赖的实体名",
    )
    resolution_strategy: str = Field(default="", description="解决策略")


class TopicDecomposition(BaseModel):
    """Decomposition of a research topic into entities and hidden sub-topics."""

    entities: list[TopicEntity] = Field(
        default_factory=list, description="议题中涉及的实体",
    )
    hidden_sub_topics: list[HiddenSubTopic] = Field(
        default_factory=list, description="需要先解决的隐藏子问题",
    )
    search_strategy_hint: str = Field(default="", description="搜索策略提示")


class DataScope(BaseModel):
    """Data boundary established by moderator before debate."""

    scope_summary: str = ""
    specific_event: str = ""
    time_range: str = ""
    key_entities: list[str] = Field(default_factory=list)
    relevance_rule: str = ""


class VerifiedResults(BaseModel):
    """Data clerk verification of search results against scope and pool."""

    verified: list[dict] = Field(default_factory=list)
    rejected: list[str] = Field(default_factory=list)
    verification_note: str = ""


class ExtractedFacts(BaseModel):
    """Key facts extracted from a web page relevant to a query."""

    key_facts: list[str] = Field(
        default_factory=list,
        description="与搜索关键词相关的关键事实列表，每条不超过100字",
    )
    summary: str = Field(
        default="",
        description="页面内容摘要（仅与查询相关的部分）",
    )


class CrossValidatedFacts(BaseModel):
    """Cross-validated facts across multiple sources."""

    validated: list[dict] = Field(
        default_factory=list,
        description="多源佐证的事实，每条含 fact 和 source_count",
    )
    unique: list[dict] = Field(
        default_factory=list,
        description="单源事实",
    )
    contradictions: list[dict] = Field(
        default_factory=list,
        description="矛盾的事实，含 conflicting_facts 和 sources",
    )
    note: str = Field(default="", description="验证说明")


class RecencyDecision(BaseModel):
    """LLM decision on whether a search needs recency filtering."""

    needs_recent: bool = Field(
        description="本次搜索是否需要最新数据（近1周内）？"
        "体育比赛、时事新闻、最新动态 → true。"
        "历史分析、理论知识、通用百科 → false。",
    )
    recency: str = Field(
        default="noLimit",
        description="时效性过滤级别：oneDay / oneWeek / oneMonth / noLimit",
    )
    reasoning: str = Field(
        default="",
        description="判断理由（一句话）",
    )


class ScreenedResults(BaseModel):
    """Results screened for relevance and consistency before deep extraction."""

    kept: list[dict] = Field(
        default_factory=list,
        description="通过筛查的结果（title, snippet, url）",
    )
    rejected: list[str] = Field(
        default_factory=list,
        description="排除原因列表",
    )
    screening_note: str = Field(default="", description="筛查说明")


class RefinementQueries(BaseModel):
    """Queries generated to resolve contradictions found in cross-validation."""

    queries: list[str] = Field(
        default_factory=list,
        description="补充搜索关键词（最多2个，由 MAX_QUERIES 约束）",
    )
    reasoning: str = Field(default="", description="为什么搜这些关键词")
    focus: str = Field(default="", description="矛盾焦点是什么")


# --- Semantic Intent Protocol ---


class PoolSufficiency(BaseModel):
    """Check whether existing data pool already answers the agent's data need."""

    sufficient: bool = False
    missing_aspects: list[str] = Field(default_factory=list)
    reasoning: str = ""


class NeedDecomposition(BaseModel):
    """Convert semantic data need into targeted search queries.

    The LLM can signal that existing data is already sufficient by setting
    sufficient=true and leaving queries empty, instead of generating
    unnecessary searches.
    """

    queries: list[str] = Field(
        default_factory=list, description="1-2 targeted search queries",
    )
    reasoning: str = ""
    sufficient: bool = Field(
        default=False,
        description="True if existing data pool already answers the need",
    )


class DataSufficiency(BaseModel):
    """Check whether fetched data sufficiently answers the agent's data need."""

    sufficient: bool = False
    gaps: list[str] = Field(default_factory=list)
    relevant_facts: list[str] = Field(default_factory=list)
    reasoning: str = ""


class DataGapDetection(BaseModel):
    """Detect if new search results reveal a critical data gap vs existing pool."""

    has_gap: bool = False
    gap_description: str = ""
    supplementary_queries: list[str] = Field(
        default_factory=list,
        description="Queries to fill the detected gap, empty if has_gap=false",
    )
    reasoning: str = ""


# --- Research outcome ---


class ResearchOutcome:
    """Result of a research pipeline with public/private data split.

    public_results: items with validated facts — shared with all agents and frontend.
    private_results: items without validated facts — kept internally for potential promotion.
    validation: cross-validation result identifying validated/unique/contradictory facts.
    """

    __slots__ = ("public_results", "private_results", "validation")

    def __init__(
        self,
        public_results: list[dict] | None = None,
        private_results: list[dict] | None = None,
        validation: "CrossValidatedFacts | None" = None,
    ):
        self.public_results = public_results or []
        self.private_results = private_results or []
        self.validation = validation or CrossValidatedFacts()
